name: "AI PR Code Review Action"
description: "Perform code reviews and comment on diffs using various AI language models."
inputs:
  model:
    description: "Model to use for AI code review"
    required: false
    default: "openai:gpt-4o"
  language:
    description: "Language to use for AI code review"
    required: false
    default: English
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "purple"
